import Head from 'next/head'
import Image from 'next/image'
import {App} from './App'
import React from 'react'

export default function Home() {
  return (
    <>
    <div >
      <Head>
        <title className=''>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./main.css"></link>
      </Head>
    
       <div>
       <div>
        
        </div>
        </div> 
      
    </div>
    <Outlet />
    </>
  )
}
